apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app1-deployment
  labels:
    app: sample-app1
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app1
      environment: development
  template:
    metadata:
      labels:
        app: sample-app1
        environment: development
    spec:
      containers:
      - name: sample-app1
        image: vad1mo/hello-world-rest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
