apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app2-deployment
  labels:
    app: sample-app2
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app2
      environment: development
  template:
    metadata:
      labels:
        app: sample-app2
        environment: development
    spec:
      containers:
      - name: sample-app2
        image:  chentex/go-rest-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
