apiVersion: v1
kind: Service
metadata:
  name: sample-app1-service-external
  labels:
    environment: development
spec:
  type: LoadBalancer
  selector:
    app: sample-app1
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
