apiVersion: v1
kind: Service
metadata:
  name: sample-app2-service-external
  labels:
    environment: development
spec:
  type: LoadBalancer
  selector:
    app: sample-app2
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
